### ISSUE TITLE
make bin fail!!!!!

### ISSUE THREAD

**Issue by Scofields** [mesos-utility/lvs-metrics#1]
github.com/google/seesaw/netlink
could not determine kind of name for C.NLM_F_DUMP_INTR
make: *** [bin] Error 2

**Comment by soarpenguin** [comment]
please put your steps and more log. tks

**Comment by Scofields** [comment]
Steps are as follows：
```
$ cd lvs-metrics
$ make bin
```

Then output the error

**Comment by wangdi244** [comment]
操作步骤：
$ cd lvs-metrics
$ make bin
在make bin的时候报错
[root@bogon lvs-metrics]# ./control build
go build -i -ldflags "-X github.com/mesos-utility/lvs-metrics/g.Version=v0.3.0" -o lvs-metrics .
# github.com/google/seesaw/netlink
Godeps/_workspace/src/github.com/google/seesaw/netlink/cfuncs.go:20:29: error: netlink/netlink.h: No such file or directory
make: *** [bin] Error 2
build error

**Comment by xuwenjie0532** [comment]
# github.com/google/seesaw/netlink
Godeps/_workspace/src/github.com/google/seesaw/netlink/cfuncs.go:20:29: fatal error: netlink/netlink.h: No such file or directory
 #include <netlink/netlink.h>
                             ^
compilation terminated.
make: *** [bin] Error 2

**Comment by soarpenguin** [comment]
The libnl3 needed in compile and production machine.

# sudo yum install -y libnl3.x86_64
or
# sudo apt-get install libnl-3-dev libnl-genl-3-dev

**Comment by tongtongyin** [comment]
> 操作步骤： $ cd lvs-metrics $ make bin 在make bin的时候报错 [root@bogon lvs-metrics]# ./control build go build -i -ldflags "-X github.com/mesos-utility/lvs-metrics/g.Version=v0.3.0" -o lvs-metrics .
> 
> # github.com/google/seesaw/netlink
> Godeps/_workspace/src/github.com/google/seesaw/netlink/cfuncs.go:20:29: error: netlink/netlink.h: No such file or directory make: *** [bin] Error 2 build error

Is this problem solved?
